### PR TITLE
Adding support to pass in other supported params from s3.upload

### PR DESCRIPTION
**Pull request by dennismonsewicz**
Adding support to pass in additional supported params for `s3.upload`

### CODE REVIEW

**Comment by dennismonsewicz** [comment]
Thanks for the module! Been a lot of fun to use!

**Comment by francismeynard** [comment]
Btw, before I merge, just need to increase the package version, will publish new version in npm repo.

**Comment by dennismonsewicz** [comment]
@francismeynard updated :)

**Comment by francismeynard** [comment]
Published new version of lambda-s3-archiver module in npm repo. Thanks! :)

**Pull request merged**
